require "spec_helper"

describe Wallet do

  # it "" do

  # Implementation is not in definitive state yet



  # Notes on exchange security
  #
  # ...or ood things to do from a procedure point of view: (# inspired by Satoshi's posts + multisig + HDW)
  #
  # Keep most of the customer funds in 1..5..n multisig addresses # (cold storage, generated offline)
  #
  # User addresses (where users will deposit btc to) will be # pregenerated by HDW seed
  # If the seed is leaked there is a procedure to regenerate user # addresses starting from a different seed
  # The seed is stored offline and transaction to move funds to # the hot wallet must be done manually
  #
  # There are two hot wallets containing our funds, that will be # used for withdrawals, a big one and a small one
  #
  # The small one will be very hot, sitting on the server (could # be a bitcoind) and will execute small btc withdrawals
  #
  # The big one will be audited 24/7 and user with role STAFF # will be in charge to approve (and sign) withdrawals
  #

end